title: <p align="center"> Imliyangla Longkumer </p>
logo: /assets/img/Untitled design.png
description: 
  <p align="center">
  <a href="https://www.linkedin.com/in/imliyangla-longkumer/">LinkedIn</a> |
  <a href="https://github.com/Imliyangla">GitHub</a>
  
  <br>   
  Passionate biochemist with a strong academic background, merging science and tech. 
  Expert in cancer research, structural biology, and bioinformatics. Proficient in Python, automation, 
  and data analysis, seeking research or industry roles.
  <br>
  </p>

  
theme: jekyll-theme-minimal
